### ISSUE TITLE
Search module doesn't search sections which contain hyphens

### ISSUE THREAD

**Issue by dlcasto** [gethugothemes/hugo-modules#12]
The search module seems to find results on sections which do not contain hyphens but two of my sections which contain hyphens (such as a section called "how-to") never returns any results. I spent a little bit of time trying to debug the JavaScript but I haven't found the root cause yet. I believe it occurs in the doSearch function when deciding which sections to filter out.

If you could look into this issue, that would be great! I can't change my section names to remove the hyphen since my website is established and that would change the URLs of those sections/pages.

I never had this issue before the Logbook theme was updated to make use of the new hugo modules.

**Comment by tfsojon** [comment]
Hi @dlcasto 
Thank you for letting me know about the issue.
Issue Solved! Please update you search module.

Let me know if there is anything else I can help you with.

**Comment by dlcasto** [comment]
Thanks for the quick fix! I appreciate it since I'm hoping to finish updating my theme from the old version. Since I am new to the Hugo modules, how do I update the modules? I tried cleaning the Hugo module cache but the local Hugo server still shows the old code. I tried a number of things including clearing the browser cache.
