### ISSUE TITLE
Multiple search matches display incorrect excerpt

### ISSUE THREAD

**Issue by aleixripoll** [gethugothemes/hugo-modules#20]
When search string has several matches, the `lastWord` variable always contains the initial match's content. For example, let's assume the search string is `"te"` and we have the following content with two matches (caps for clarity):

"la**TE**r they go their separa**TE** ways"

"separate" becomes "separa**LA**te" in the search result excerpt, as `matchIndex` will always point to the first match, but the `replace` function replaces every occurrence because of the "g" (global) `regex` modifier:

https://github.com/gethugothemes/hugo-modules/blob/c3e6f1eb8b7b49571bf0d102cd2647beac1b5937/search/assets/js/search.js#L231-L233

As a workaround, I used a regex without the "global" flag in that block of code. Now it just highlights the first occurrence which is fine by me, but there might be a better solution.

```
          return matchedContent.replace(
            new RegExp(searchString, "i"),
            (match) => lastWord + `<mark>${match}</mark>`
          );
```

**Comment by tfsomrat** [comment]
Hey @aleixripoll, Thanks for finding this issue and giving a suggestion. It would be great if you do a PR.
