### ISSUE TITLE
Possibly icons need to be in increments of 48px

### ISSUE THREAD

**Issue by neural-loop** [gethugothemes/hugo-modules#21]
https://github.com/gethugothemes/hugo-modules/blob/2e720c5b7e8b109f5fb6ab3eedca67e838e90992/images/layouts/partials/favicon.html#L17

I was trying to figure out why the icon stopped appearing in a recently launched site:

https://developers.google.com/search/docs/appearance/favicon-in-search?sjid=13436093623384414928-NA&visit_id=638325057513215794-1631924546&rd=1

> Your favicon must be a multiple of 48px square, for example: 48x48px, 96x96px, 144x144px and so on.

**Comment by tfsomrat** [comment]
hey @neural-loop, thanks for your concern. I just updated the sizes. please update your module to see the effect.
