### ISSUE TITLE
Search XSS vulerability

### ISSUE THREAD

**Issue by ma-ha** [gethugothemes/hugo-modules#22]
With search enabled, using the "s=" URL parameter it is possible to inject and execute code in the client browser.
Example: `https://my.hugo.page/?s=sxss1'<%2F"></b><img src=1 onerror=alert(document.domain)>`

The "s=" parameter should be removed or fixed using `encodeURIComponent()` before inserting the query parameter into the DOM.

**Comment by ma-ha** [comment]
This fix works:
https://github.com/gethugothemes/hugo-modules/compare/master...ma-ha:hugo-modules:master

**Comment by ma-ha** [comment]
This fix is better: https://github.com/ma-ha/hugo-modules/commit/249f841a33d02893dd1424baa05cc11f8a47af7f

**Comment by tfsomrat** [comment]
Hey @ma-ha , i have added the changes https://github.com/gethugothemes/hugo-modules/commit/37017d01a181089a951e8f5d0a16c89ce234688e

thanks
