### ISSUE TITLE
Email Obfuscation to prevent spam bots

### ISSUE THREAD

**Issue by gedw99** [gethugothemes/hugo-modules#24]
Email harvesters and other bots roam the Internet looking for email addresses to add to lists that target recipients for spam. This trend results in an increasing amount of unwanted email.

So need to layer on the plain-text obfuscation technique.

Here's some techniques: https://web.archive.org/web/20180908103745/http://techblog.tilllate.com/2008/07/20/ten-methods-to-obfuscate-e-mail-addresses-compared/

**Comment by RoneoOrg** [comment]
Related: https://github.com/martignoni/hugo-cloak-email

**Comment by tfsomrat** [comment]
Hey @gedw99, Good news, we have created a cloak-contact shortcode. check it out: https://github.com/gethugothemes/hugo-modules/tree/master/shortcodes/cloak-contact

**Comment by gedw99** [comment]
thanks @tfsomrat for the heads up. Will try not out !
