### ISSUE TITLE
Build error related to Page Bundles images after commit 27be1f6

### ISSUE THREAD

**Issue by alex-feel** [gethugothemes/hugo-modules#30]
An issue has arisen following the commit 27be1f6. Since this commit, I've been encountering a specific build error related to template rendering in my Hugo site that wasn't present before. The error occurs during the site rendering process, particularly when processing the `list.searchindex.json` template. Here's the error message:

```bash
Error: error building site: render: failed to render pages: render of "home" failed: "hugo-modules/search/layouts/_default/list.searchindex.json:25:67": execute of template failed: template: _default/list.searchindex.json:25:67: executing "_default/list.searchindex.json" at <.Page>: can't evaluate field Page in type string
```

Before this commit, my site was built without any issues. However, there was a pre-existing problem where images were not displaying in the search results for entries using Page Bundles. The front matter for these entries is typically as follows:

```yaml
---
title: 'Some Title'
images: ['image.png']
...
---
```

For items where the front matter is formatted like this:

```yaml
---
title: 'Some Title'
images: ['/images/image.png']
...
---
```

images display correctly in the search results, provided that the `list.searchindex.json` code is as it was before the commit 27be1f6.

It seems that the recent changes might have affected how Page Bundles and their associated images are handled or rendered. I would appreciate any assistance or guidance on resolving this error to restore the site's functionality and ensure images are displayed correctly in the search results.

**Comment by tfsomrat** [comment]
Hey @alex-feel, thank you.
