### ISSUE TITLE
[SECURITY] Search module is vulnerable to XSS

### ISSUE THREAD

**Issue by harm0nious** [gethugothemes/hugo-modules#32]
The `${searchString}` can cause a XSS vulnerability while doing a search, for example, using the payload `<img/src/onerror=prompt(8)>
`:

![image](https://github.com/gethugothemes/hugo-modules/assets/15961866/bd361037-d53f-437a-9409-9143ae22d3ac)

**Comment by tfsomrat** [comment]
Hey @harm0nious, Thanks for your concern. this issue has been fixed. please update your module.
