### ISSUE TITLE
Cookie consent shows leads to uncaught ReferenceError: Cookies is not defined

### ISSUE THREAD

**Issue by thierry-tct** [gethugothemes/hugo-modules#33]
Cookie consent usage leads to the error: `uncaught ReferenceError: Cookies is not defined`

Perhaps the documentation should be updated to have:
```
<script src="
https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js
"></script>
{{ partialCached "cookie-consent.html" . }}
```

instead of 
```
{{ partialCached "cookie-consent.html" . }}
```

**Comment by tfsomrat** [comment]
hey @thierry-tct, thanks for your concern. you don't need that script to show cookie consent, just make sure you have added the config correctly

```
[[params.plugins.js]]
link = "plugins/cookie.js"
```

and if the `lazy=true`, then make it false. it will work. thanks

**Comment by thierry-tct** [comment]
Hey @tfsomrat,

Thank you. Removing the `lazy=true` solved the issue
