### ISSUE TITLE
Tabs header are not responsive

### ISSUE THREAD

**Issue by thierry-tct** [gethugothemes/hugo-modules#37]
When there are many tabs, and the webpage is viewed on a small screen (like mobile phone), the right most tabs overflow and are not (or partially) seen.
Maybe the tab headers can be stacked for small screens. 

{{< tabs "tab-group-name" >}}
{{< tab "first-long-name" >}}
First Tab 1
{{< /tab >}}

{{< tab "second" >}}
Second Tab 1
{{< /tab >}}

{{< tab "third" >}}
Third Tab 1
{{< /tab >}}

{{< tab "fourth" >}}
Fourth Tab 1
{{< /tab >}}
{{< /tabs >}}

**Comment by tfsomrat** [comment]
Hey @thierry-tct, The tab is actually responsive on it's own way. If you need to stack the tab headers, you can overwrite the CSS by using `tab-nav` class. thanks

**Comment by thierry-tct** [comment]
Hey @tfsomrat , 
Thanks, i will do so
