### ISSUE TITLE
Support for LinkedIn, Google, Pinterest in Social-Share

### ISSUE THREAD

**Issue by thierry-tct** [gethugothemes/hugo-modules#39]
Are there plans to support LinkedIn, Google, Pinterest (or any other social media listed in the scss file) in the [social-share partial](https://github.com/gethugothemes/hugo-modules/blob/master/components/social-share/layouts/partials/social-share.html)?

I can make a PR if you want.
Thanks

**Comment by tfsomrat** [comment]
Hey @thierry-tct, Thanks for your interest. we will be very happy if you contribute here. but please skip the Google+, because it's dead. and also you can update the twitter logo to close the issue #38

**Comment by thierry-tct** [comment]
Hey @tfsomrat , Thanks, I created a [PR](https://github.com/gethugothemes/hugo-modules/pull/40) for the two tickets
