### ISSUE TITLE
Imports for shortcodes doesn't work suddenly 

### ISSUE THREAD

**Issue by skaftanis** [gethugothemes/hugo-modules#4]
Suddenly, the shortcodes stopped working. 

I have errors like this and I can complete the build: 

`
failed to extract shortcode: template for shortcode "changelog" not found
`

I use andromeda premium theme.

**Comment by tfsojon** [comment]
@skaftanis Are you still facing this problem?

**Comment by tfsojon** [comment]
> I fixed it using the following command (many times).
> 
> `hugo mod clean && hugo mod get -u ./... && hugo mod tidy`

Yes you are right. We need to clear Hugo Mod cache; That's what you did. Thanks for your feedback.
