### ISSUE TITLE
no linkedin ? 

### ISSUE THREAD

**Issue by tonhe** [gethugothemes/hugo-modules#43]
would be nice to include that in social-share

**Comment by jonniehack** [comment]
In your params.toml, try this:

[[social]]
title = "LinkedIn"
icon = "fa-brands fa-linkedin-in" 
link = "https://www.linkedin.com/in/YOURNAME"

**Comment by tfsomrat** [comment]
Hey @tonhe , we have linkedin share in this module. please update your module to get linkedin. thanks
