### ISSUE TITLE
Accordian doesnt display all code.

### ISSUE THREAD

**Issue by jonniehack** [gethugothemes/hugo-modules#45]
When I moved from using "Collapse" to using "Accordion" correctly, I noticed that the chunk of code I placed into the new "Accordion" shortcode wasn't all displayed.  Half the code was cut off.  Can this be fixed?

**Comment by tfsomrat** [comment]
did you removed all codes from `collapse` completely? please attach a screenshot.

**Comment by jonniehack** [comment]
I believe I did remove all codes, yes.  Did you forget to attach a screenshot?  Could you instruct exactly what to remove?

**Comment by tfsomrat** [comment]
I want you to attach a screenshot of broken accordion. and also give me a repository link so that I can test it

**Comment by jonniehack** [comment]
I cant share the repo with you however this is my process.

Shortcode called like this

{{< tabs >}}
{{< tab "1" >}}
{{< accordion title="This is an accordion" >}}
```sql
LOTS OF CODE HERE
```
{{< /accordion >}}
{{< /tab >}}
{{< /tabs >}}

I have noticed, that once rendered half my code is missing, its as if the accordion has a set size.  If I zoom out, I can see that more is displayed but its unreadable, zoom back in and more code is omitted.

**Comment by tfsomrat** [comment]
Is everything works if you don't use it inside the Tab?

**Comment by jonniehack** [comment]
No same behaviour outside of the tab

**Comment by jonniehack** [comment]
Have you been able to reproduce this?

**Comment by tfsomrat** [comment]
Hey @jonniehack, we have updated logbook hugo with for this module. please re-download it from your dashboard. thanks

**Comment by jonniehack** [comment]
I have updated Logbook and this module, and the problem remains for me.  I do not belive this is fixed.

**Comment by tfsomrat** [comment]
Hey @jonniehack, this is the latest demo of Logbook theme, and everything is working as expected https://demo.gethugothemes.com/logbook/site/elements/

**Comment by jonniehack** [comment]
I have run **npm run update-modules**. It shows me I have version
![image](https://github.com/gethugothemes/hugo-modules/assets/13187084/4886dccd-c4e7-44c5-ae86-b6a4f02b106a)
Yet I am still having problems.  
The [demo elements page](https://demo.gethugothemes.com/logbook/site/elements/) only has a couple of lines inside the accordians, this works fine.  Have a go at dropping **50+** lines of codeblock inside an accordian and see if it still works.  The limit on lines seems to be around 40 lines and no manner of updating Logbook or the modules seems to work.  I have posts ready to publish but the limitation on accordians is frustrating.  I have to shorten my code to get the things.  I am unable to shorten one code block inside accordians to fewer than 44 lines and it does not render it all. it just it off completely so I still think this needs addressing.

**Comment by tfsomrat** [comment]
Hey @jonniehack, thanks for your clear information. I have fixed it. please update your modules one more time, it should work perfectly.
