### ISSUE TITLE
Notice doesnt display inside accordion or collapse

### ISSUE THREAD

**Issue by jonniehack** [gethugothemes/hugo-modules#46]
When I insert a "Notice" inside a tab, the notice is not displayed correctly. 

See attached Image. Same code used, so its not how I've configured the notice.
![brokennotice](https://github.com/gethugothemes/hugo-modules/assets/13187084/74f26280-aee7-490d-99c1-3f8e4875d6ee)

**Comment by tfsomrat** [comment]
Hey @jonniehack, thanks for the findings. I fixed the issue. please update your modules.

**Comment by jonniehack** [comment]
hi @tfsomrat - thanks for the update.  According to the shortcode documentation, I need to have the following which I already do.

![2024-02-15 08_48_51-hugo-modules_shortcodes_notice at master · gethugothemes_hugo-modules and 1 more](https://github.com/gethugothemes/hugo-modules/assets/13187084/74c6b416-e52b-4cf6-926a-cb0ed381e80a)

I noticed you updated the notice.html, so I downloaded this and placed into my \themes\logbook-hugo\layouts\shortcodes, re-ran Hugo Server, however I am still seeing the same behaviour.

Have I Missed something?

**Comment by tfsomrat** [comment]
I have tested it here, and everything works fine https://github.com/zeon-studio/hugoplate/

**Comment by jonniehack** [comment]
I do appreciate that you tested it there and it works fine, however, I am not experiencing this.   I am new to this so please bear with me.  I am using Logbook theme.  

Could you please advise if I have missed anything from your first instruction to update the module?  Perhaps I haven't updated correctly.  My **module.toml** contains this:

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

my theme\assets\style.scss contains this

@import 'notice';

and I have downloaded the notice.html to \themes\logbook-hugo\layouts\shortcodes

Do I need to do anything else to **update** the module after your changes?

**Comment by jonniehack** [comment]
I have figured this out, it now works.  I had to update Tabs too.

Thank you for fixing it @tfsomrat
