### ISSUE TITLE
Search through the whole website

### ISSUE THREAD

**Issue by eqslab** [gethugothemes/hugo-modules#47]
Hi, guys.

I have a question. Is it possible to organize a search throughout the whole website, without connection to sections or other internal structure, as I am having difficulties with it. I use some hugo theme for my website and heavily modified it. Whatever I've done so far, search was working only in some particular folders (i.e. `"Blogs"` and `"People"`) which probably has some "proper" internal structure (`_index.md`, `list.html` template, `single.html` template) and not for the whole website. I also have general single `md` files in the root folder and would like the search to work on them too. Is it possible to implement?

Thank you in advance!

**Comment by eqslab** [comment]
**Addition**: This is how the website structure looks like. Although I added option `include_all_sections = true`, the search works in "People" and "News" folders only.
![2024-02-17_13-11](https://github.com/gethugothemes/hugo-modules/assets/157070559/103e3338-1066-44be-bd91-18c92854a1f3)

**Comment by tfsomrat** [comment]
Hey @eqslab, the search is designed to be searched within single pages. If you need to include list page also, you need to customize the search script and json generator. you can hire us to customize your Hugo website at https://gethugothemes.com/get-a-quote 
Thanks

**Comment by eqslab** [comment]
Got it. Thanks for the answer.
