### ISSUE TITLE
Outline buttons acting strange

### ISSUE THREAD

**Issue by jonniehack** [gethugothemes/hugo-modules#48]
I've recently updated my module from **buttons** to **button**. The button module is behaving funny when using the outline style which I prefer.  Your documentation doesnt state I need to update my style.cscss with "@import **button**;".  So I left the "@Import button**s**;" alone.  On the grid view homepage, buttons are working as they should.  

Following your instructions, the following occurs when I try to use a button with an outline style in a post

![image](https://github.com/gethugothemes/hugo-modules/assets/13187084/06025ada-400b-47c2-950e-4849d4141b3e)
(not all the outline is working the button should have a full blue outline on my test, but its missing the bottom line)

In addition to this button text isnt changing with the theme, to white, like it should when I hover over the button.
![image](https://github.com/gethugothemes/hugo-modules/assets/13187084/3ae3cb3a-7fa2-47f5-a331-00413980cace)

Params are set as they should be.

**Comment by tfsomrat** [comment]
Hey @jonniehack, I am sorry to hear that. can you tell me on which theme you are using this module?

**Comment by tfsomrat** [comment]
Hey @jonniehack, Sorry to hear that. in your theme, search for `.content` class (maybe in the `_common.scss` file). and in that class, you will find styles for `a` tag. just replace the `a` with `a:not(.btn)`, it will solve your issue.
