### ISSUE TITLE
[search] Search modal contains hard-coded texts

### ISSUE THREAD

**Issue by Frank3K** [gethugothemes/hugo-modules#49]
Not all texts in the search modal can be translated. See this one in Dutch:

![image](https://github.com/zeon-studio/hugoplate/assets/8014077/d6c6dc0a-8b2c-43d4-91d4-c8e088f6b154)

Sources:

https://github.com/gethugothemes/hugo-modules/blob/6c6ca12add7dfc95f52dd61f8c6fdc9abda0092d/search/layouts/partials/search-modal.html#L83
https://github.com/gethugothemes/hugo-modules/blob/6c6ca12add7dfc95f52dd61f8c6fdc9abda0092d/search/layouts/partials/search-modal.html#L99
https://github.com/gethugothemes/hugo-modules/blob/6c6ca12add7dfc95f52dd61f8c6fdc9abda0092d/search/layouts/partials/search-modal.html#L103

**Comment by tfsomrat** [comment]
Thanks for your concern. I have updated the module. please check the search readme file. thanks
