### ISSUE TITLE
[tabs] Single paragraph not wrapped in `p` tag

### ISSUE THREAD

**Issue by Qup42** [gethugothemes/hugo-modules#51]
The tabs use [markdownify](https://gohugo.io/functions/transform/markdownify/) to transform the content of an individual tab to markdown. If the content consists of multiple paragraphs then all paragraphs are individually wrapped in `p` HTML tags. If the content is only a single paragraph then the content is now wrapped in a `p` tag. This inconsistency causes problems in the way that I use and style the tabs. I would prefer it, if the tabs content would always be wrapped in a `p`.

This can be achieved by using `Page.RenderString` and setting `display` to `block` like this

```diff
<         {{ .content  | markdownify }}
---
>         {{ .content  | $.Page.RenderString (dict "display" "block") }}
```

Would you be open to this?

**Comment by tfsomrat** [comment]
Thanks for your suggestion. I fixed it.
