### ISSUE TITLE
Whitespaces in og:image:type

### ISSUE THREAD

**Issue by dehydr8** [gethugothemes/hugo-modules#53]
The template `basic-seo.html` adds whitespaces to the generated `og:image:type` meta tag.

https://github.com/gethugothemes/hugo-modules/blob/612e47c108d744403a790fa4028dd2f28a439dc2/seo-tools/basic-seo/layouts/partials/basic-seo.html#L139-L145

This produces an output like this:
```html
<meta property="og:image:type" content="image/
  .png
">
```

The whitespaces can be trimmed by adding `{{- -}}` to the template.

Also note that the extension contains a `.` (dot) which makes the type incorrect.

**Comment by tfsomrat** [comment]
Hey @dehydr8, can you create a PR to this open-source project? it will be great. thanks

**Comment by tfsomrat** [comment]
We have update the module. thanks
