### ISSUE TITLE
Deprecated parameters used in basic-seo

### ISSUE THREAD

**Issue by sapradhan** [gethugothemes/hugo-modules#63]
Getting this warning when using basic-seo partial
 
```
WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.
WARN  deprecated: .Site.Authors was deprecated in Hugo v0.124.0 and will be removed in a future release. Use taxonomies instead.
```

I believe it is related to these lines 

https://github.com/gethugothemes/hugo-modules/blob/49ae4a26e064a1e6b8bd0a23f5c81b9a93e75c96/seo-tools/basic-seo/layouts/partials/basic-seo.html#L164-L169

**Comment by tfsomrat** [comment]
Hey @sapradhan, Thank you for notifying me. I have fixed the issue.
