### ISSUE TITLE
Banner loading attribute not updating from "lazy" to "eager" or default

### ISSUE THREAD

**Issue by starraiderx** [gethugothemes/hugo-modules#7]
### Description:
I am trying to change the loading attribute of the banner from "lazy" to "eager" or to the default value by setting an empty string. However, updating the attribute does not seem to have any effect. I have already updated all the relevant modules using yarn update.

### Steps to reproduce:

1.     Update the loading attribute in the banner partial by replacing "lazy" with "eager" or an empty string ("").
2.     Save the changes and build the project.
3.     Observe that the banner loading behavior remains unchanged.

### Expected behavior:
Changing the loading attribute in the banner partial should update the loading behavior of the banner image to either "eager" or the default value.

### Actual behavior:
The banner loading behavior remains unchanged even after updating the attribute.

### Code snippet:

```<!-- banner -->
{{ with .Params.banner }}
<section class="banner">
  <div class="container">
    ...
        {{ partial "image" (dict "Src" .image "Loading" "eager" "Alt" .title "Class" "rounded-2") }}
  ...
</section>
{{ end }}
<!-- /banner -->
```
Additional context:
I have tried updating all the modules using yarn update but the issue persists. Please let me know if there's any other information needed to resolve this issue.

**Comment by tfsomrat** [comment]
hello @starraiderx 

Thanks for raising this issue. I have fixed that. please update your modules one more time.
